---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    nodepool: my-cluster-md-0
  name: my-cluster-md-0
  namespace: default
spec:
  clusterName: my-cluster
  replicas: 0
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        nodepool: my-cluster-md-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: my-cluster-workers
      clusterName: my-cluster
      failureDomain: fsn1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: my-cluster-md-0
      version: 1.30.0
