---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: my-cluster-control-plane
spec:
  version: v1.30.0
  replicas: 1
  infrastructureTemplate:
    kind: HCloudMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    name: my-cluster-control-plane
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.7.1
