---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: my-cluster-workers
spec:
  template:
    spec:
      generateType: join
      talosVersion: v1.7.1
      configPatches:
      - op: add
        path: /machine/kubelet/registerWithFQDN
        value: true
      - op: add
        path: /cluster/externalCloudProvider
        value:
          enabled: true
